import uuid
from sqlalchemy import Column, String, Integer, Boolean
from sqlalchemy.dialects.postgresql import UUID
from app.db.base import Base


class University(Base):
    __tablename__ = "universities"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    name = Column(String, nullable=False)
    country = Column(String, nullable=False)
    degree = Column(String, nullable=False)  # Masters / Bachelors
    field = Column(String, nullable=False)

    tuition_min = Column(Integer, nullable=False)
    tuition_max = Column(Integer, nullable=False)

    difficulty = Column(String, nullable=False)  # LOW / MEDIUM / HIGH
    # Mark universities generated by the AI discovery flow so we can safely refresh them
    generated_by_ai = Column(Boolean, nullable=False, default=False, server_default='false', index=True)
